site_name: Alatting API Docs
dev_addr: 0.0.0.0:8001
# theme: simplex

pages:
- 首页: 'index.md'
- 开发环境: 'develop.md'
- API列表: 'api_list.md'

- 基础 API(作废):
    - '用户认证': 'base/auth.md'
    - '用户信息': 'base/profile.md'
    - '上传': 'base/upload.md'
    # - '分页': 'base/pagination.md'
- 海报 API(作废):
    - '基础资源API': 'poster/resource.md'
    - '海报接口API': 'poster/poster.md'
